require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe FoodsController do

  def mock_food(stubs={})
    @mock_food ||= mock_model(Food, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all foods as @foods" do
      Food.stub(:all) { [mock_food] }
      get :index
      assigns(:foods).should eq([mock_food])
    end
  end

  describe "GET show" do
    it "assigns the requested food as @food" do
      Food.stub(:find).with("37") { mock_food }
      get :show, :id => "37"
      assigns(:food).should be(mock_food)
    end
  end

  describe "GET new" do
    it "assigns a new food as @food" do
      Food.stub(:new) { mock_food }
      get :new
      assigns(:food).should be(mock_food)
    end
  end

  describe "GET edit" do
    it "assigns the requested food as @food" do
      Food.stub(:find).with("37") { mock_food }
      get :edit, :id => "37"
      assigns(:food).should be(mock_food)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created food as @food" do
        Food.stub(:new).with({'these' => 'params'}) { mock_food(:save => true) }
        post :create, :food => {'these' => 'params'}
        assigns(:food).should be(mock_food)
      end

      it "redirects to the created food" do
        Food.stub(:new) { mock_food(:save => true) }
        post :create, :food => {}
        response.should redirect_to(food_url(mock_food))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved food as @food" do
        Food.stub(:new).with({'these' => 'params'}) { mock_food(:save => false) }
        post :create, :food => {'these' => 'params'}
        assigns(:food).should be(mock_food)
      end

      it "re-renders the 'new' template" do
        Food.stub(:new) { mock_food(:save => false) }
        post :create, :food => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested food" do
        Food.stub(:find).with("37") { mock_food }
        mock_food.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :food => {'these' => 'params'}
      end

      it "assigns the requested food as @food" do
        Food.stub(:find) { mock_food(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:food).should be(mock_food)
      end

      it "redirects to the food" do
        Food.stub(:find) { mock_food(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(food_url(mock_food))
      end
    end

    describe "with invalid params" do
      it "assigns the food as @food" do
        Food.stub(:find) { mock_food(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:food).should be(mock_food)
      end

      it "re-renders the 'edit' template" do
        Food.stub(:find) { mock_food(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested food" do
      Food.stub(:find).with("37") { mock_food }
      mock_food.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the foods list" do
      Food.stub(:find) { mock_food }
      delete :destroy, :id => "1"
      response.should redirect_to(foods_url)
    end
  end

end
